
ANTHROPIC_API_KEY = "sk-YOUR_ANTHROPIC_API_KEY"
GROQ_API_KEY = "gsk_YOUR_GROQ_API_KEY"
HUGGINGFACE_API_TOKEN = "hf_YOUR_HUGGINGFACE_API_TOKEN"
MODEL_NAME = "claude-3-opus-20240229" # Example Anthropic model
TEMPERATURE = 0.7
MAX_TOKENS = 8192
